# Generated by Django 2.1.3 on 2019-05-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('favorites', models.FileField(upload_to='favs/')),
                ('image_url', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('directions_url', models.URLField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('calories', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
