# Generated by Django 2.1.3 on 2019-05-06 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='calories',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='image_url',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipe_img/'),
        ),
    ]
