# Generated by Django 2.2.4 on 2019-09-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190506_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='favorites',
            field=models.FileField(upload_to='favorites/'),
        ),
    ]
