# Generated by Django 2.2.5 on 2019-09-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190902_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='total_time',
        ),
    ]
